app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms import TextAreaField, TextField, SelectField
from wtforms.validators import DataRequired, ValidationError, Email, EqualTo
from wtforms.validators import Length
from app.models import User
from flask_babel import lazy_gettext as _l
from flask_babel import _
from flask import request, flash
from app import db
from flask_ckeditor import CKEditorField


class EditProfileForm(FlaskForm):
    username = StringField(_l('Username'), validators=[DataRequired()])
    about_me = CKEditorField(_l('About me'), validators=[Length(min=0, max=140)])
    email = StringField(_l('Email Address'), validators=[DataRequired(), Email()])
    submit = SubmitField(_l('Submit'))

    def __init__(self, original_username, original_email, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.original_username = original_username
        self.original_email = original_email

    def validate_username(self, username):
        if username.data != self.original_username:
            user = User.query.filter_by(username=self.username.data).first()
            if user is not None:
                error_message = _l('Please use a different username.')
                flash(_l(error_message))
                raise ValidationError(_l(error_message))

    def validate_email(self, email):
        if email.data != self.original_email:
            email = User.query.filter_by(email=self.email.data).first()
            if email is not None:
                error_message = _l('Please use a different email address.')
                flash(_l(error_message))
                raise ValidationError(_l(error_message))


class PostForm(FlaskForm):
    title = TextField(
        _l('Header'),
        validators=[DataRequired(), Length(min=1, max=128)]
    )
    post = CKEditorField(
        _l('Say something')
    )
    category = SelectField(_l('Category'))
    submit = SubmitField(_l('Submit'))

class EditPostForm(FlaskForm):
    title = TextField(
        _l('Header'),
        validators=[DataRequired(), Length(min=1, max=128)]
    )
    post = CKEditorField(
        _l('Say something'),
        validators=[DataRequired()]
    )
    submit = SubmitField(_l('Submit'))


class CategoryForm(FlaskForm):
    title = TextField(
        _l('Title'),
        validators=[Length(min=5, max=128)]
    )
    description = CKEditorField(
        _l('Description')
    )
    submit = SubmitField(_l('Submit'))


class EditCategoryForm(FlaskForm):
    title = TextField(
        _l('Title'),
        validators=[Length(min=5, max=128)]
    )
    description = CKEditorField(
        _l('Description')
    )
    submit = SubmitField(_l('Submit'))


class ChangePasswordForm(FlaskForm):
    password = PasswordField(_l('Password'), validators=[DataRequired(), Length(min=12, max=128)])
    password_repeat = PasswordField(
        _l('Repeat Password'),
        validators=[DataRequired(), EqualTo('password'), Length(min=12, max=128)]
    )
    submit = SubmitField(_l('Register'))


class DeletePostApproveForm(FlaskForm):
    choice = BooleanField(
        _l('Are you sure you want to delete the post?')
    )
    submit = SubmitField(_l('Submit'))

class CommentForm(FlaskForm):
    body = TextAreaField(_l('Write here your comment'))
    submit = SubmitField(_l('Submit'))

class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'csrf_enabled' not in kwargs:
            kwargs['csrf_enabled'] = False
        super(SearchForm, self).__init__(*args, **kwargs)

class MessageForm(FlaskForm):
    message = CKEditorField(
        _l('Message'),
        validators=[
            Length(min=0, max=140)
        ]
    )
    submit = SubmitField(_l('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import os
from werkzeug.utils import secure_filename
from flask import render_template, flash, redirect, url_for, request, current_app
from flask import send_from_directory
from app import db
from app.main.forms import EditProfileForm, EditCategoryForm
from flask_login import current_user, login_required
from app.models import User
from datetime import datetime
from app.main.forms import PostForm
from app.models import Post, Rate, Category
from flask_babel import lazy_gettext as _l
from flask import g, make_response
from flask_babel import get_locale
from guess_language import guess_language
from app.main import bp
from app.main.forms import SearchForm
from flask_babel import _
from app.main.forms import MessageForm
from app.models import Message, Notification
from flask import jsonify
from app.main.forms import CommentForm, EditPostForm, DeletePostApproveForm
from app.main.forms import ChangePasswordForm, CategoryForm
from app.models import Comment
from sqlalchemy.sql import func
import random
from flask_ckeditor import upload_success, upload_fail
from flask_sqlalchemy import sqlalchemy

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())


@bp.teardown_request
def shutdown_session(exception=None):
    db.session.flush()
    db.session.remove()


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    comments = Comment.query.all()
    username = User.query.filter_by(username=current_user.username).first()
    page = request.args.get('page', 1, type=int)
    posts = current_user.followed_posts().paginate(
        page,
        current_app.config['POSTS_PER_PAGE'],
        False
    )

    categories = Category.query.all()
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template(
        'main/index.html.j2',
        title=_l('The Home Page'),
        posts=posts.items,
        next_url=next_url,
        prev_url=prev_url,
        comments=comments,
        username=username,
        categories=categories
    )


# User page
@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.all()
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
        page,
        current_app.config['POSTS_PER_PAGE'],
        False
    )
    categories = Category.query.all()
    next_url = url_for('main.user', username=user.username, page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.user', username=user.username, page=posts.prev_num) \
        if posts.has_prev else None

    return render_template(
        'main/user.html.j2',
        user=user,
        posts=posts.items,
        next_url=next_url,
        prev_url=prev_url,
        comments=comments,
        categories=categories
    )


# User profile edit
@bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(current_user.username, current_user.email)
    comments = Comment.query.filter_by(username=current_user.username).all()
    if form.validate_on_submit():
        if comments:
            for comment in comments:
                comment.username = current_user.username
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        current_user.email = form.email.data
        db.session.commit()
        flash(_l('Your changes have been saved'))
        return redirect(url_for('main.edit_profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
        form.email.data = current_user.email
    return render_template('main/edit_profile.html.j2', title='Edit Profile', form=form)


@bp.route('/password/change/<username>', methods=['GET', 'POST'])
@login_required
def change_password(username):
    form = ChangePasswordForm()
    user = User.query.filter_by(username=username).first()
    password = form.password.data
    is_valid = ''
    if password:
        is_valid = User.check_password_validity(password)
        if form.validate_on_submit() and is_valid[0]:
            user.set_password(password)
            db.session.commit()
            flash(_l('Your password has been changed.'))
            return redirect(url_for('main.user', username=current_user.username))
        elif form.password.data != form.password_repeat.data:
            flash(_l('Passwords do not match. Try again'))
        else:
            flash(_l('Check your motherfucking password.'))
            if is_valid[1]['length_error']:
                flash(_l('Check your password length.'))
            if is_valid[1]['digit_error']:
                flash(_l('Password must include at least one digit.'))
            if is_valid[1]['uppercase_error']:
                flash(_l('Password must include at least one uppercase letter.'))
            if is_valid[1]['lowercase_error']:
                flash(_l('Password must include at least one lowercase letter.'))
            if is_valid[1]['symbol_error']:
                flash(_l('Password must include at least one special symbol.'))
            password = ''

    return render_template('main/change_password.html.j2', form=form)


@bp.route('/explore')
@login_required
def explore():
    comments = Comment.query.all()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.timestamp.desc()).paginate(
        page,
        current_app.config['POSTS_PER_PAGE'],
        False
    )
    categories = Category.query.all()
    next_url = url_for('main.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template(
        'main/index.html.j2',
        title=_l('Explore'),
        posts=posts.items,
        next_url=next_url,
        prev_url=prev_url,
        comments=comments,
        categories=categories
    )


@bp.route('/search')
@login_required
def search():
    comments = Comment.query.all()
    if not g.search_form.validate():
        return redirect(url_for('main.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])
    users, total = User.search(g.search_form.q.data, page,
                               current_app.config['POSTS_PER_PAGE'])

    next_url = url_for('main.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('main.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None

    if users:
        if users.count() < 1:
            users = False
        if posts.count() < 1:
            posts = False
        return render_template(
            'search/search.html.j2',
            title=_('Search'),
            posts=posts,
            next_url=next_url,
            prev_url=prev_url,
            comments=comments,
            users=users
        )
    return render_template(
        'search/search.html.j2',
        title=_('Search'),
        posts=posts,
        next_url=next_url,
        prev_url=prev_url,
        comments=comments
    )


@bp.route('/user/<username>/popup')
@login_required
def user_popup(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template(template_name_or_list='main/user_popup.html.j2', user=user)


@bp.route('/follow/<username>')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('main.index'))
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {}!'.format(username))
    return redirect(url_for('main.user', username=username))


@bp.route('/unfollow/<username>')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found.'.format(username))
        return redirect(url_for('index'))
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {}.'.format(username))
    return redirect(url_for('main.user', username=username))

@bp.route('/send/message/<recipient>', methods=['GET', 'POST'])
@login_required
def send_message(recipient):
    user = User.query.filter_by(username=recipient).first_or_404()
    form = MessageForm()
    if form.validate_on_submit():
        msg = Message(
            author=current_user,
            recipient=user,
            body=form.message.data
        )
        db.session.add(msg)
        user.add_notification('unread_message_count', user.new_messages())
        db.session.commit()
        flash(_('Your message has been sent.'))
        return redirect(url_for('main.user', username=recipient))
    return render_template(
        'messages/send_message.html.j2',
        title=_('Send message'),
        form=form,
        recipient=recipient
    )


@bp.route('/messages')
@login_required
def messages():
    comments = Comment.query.all()
    current_user.last_messages_read_time = datetime.utcnow()

app/templates/main/_post.html.j2
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <span class="user_popup">
        <img src="{{ post.author.avatar(70) }}" alt="">
        <a href="{{ url_for('main.user', username=post.author.username) }}">
          {{ post.author.username }}
        </a>
      </span>
      {{ _('said') }} {{ moment(post.timestamp).fromNow() }}
      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h1>{{ post.title }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      {{ post.body }}

      <br>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <span class="badge badge-secondary">{{ total_likes }} {{ _('Users liked this post') }}</span>
      <span class="badge badge-secondary">{{ total_dislikes }} {{ _('Users disliked this post') }}</span>

      {% if post.language and post.language != g.locale %}
        <br><br>
        <a href="#">{{ _('Translate') }}</a>
      {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      {% if post.author.id == current_user.id %}
        <a class="btn btn-success" href="{{ url_for('main.edit_post', id=post.id) }}">{{ _("Edit Post") }}</a>
        <a class="btn btn-success" href="{{ url_for('main.delete_post', id=post.id) }}">{{ _("Delete Post") }}</a>
      {% endif %}
      <a class="btn btn-success" href="{{ url_for('main.set_like', id=post.id) }}">{{ _("Like") }}</a>
      <a class="btn btn-danger" href="{{ url_for('main.set_dislike', id=post.id) }}">{{ _("Dislike") }}</a>
      <a class="btn btn-primary" href="{{ url_for('main.send_comment', post_id=post.id) }}">{{ _("Add Comment") }}</a>
      <br><br>
    </div>
  </div>
  {% if comments %}
    {% for comment in comments %}
      {% if comment.post_id == post.id %}
      <div class="row">
        <div class="col-lg-12">
          <a href="{{ url_for('main.user', username=comment.username) }}">{{ comment.username }}</a>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
            {{ comment.body }}<br>
        </div>
      </div>
      {% endif %}
    {% endfor %}
  {% else %}
    <div class="row">
      <div class="col-lg-12">
          <h1>Comments are not available</h1>
      </div>
    </div>
  {% endif %}

  {% if message %}
    {{ message }}
  {% endif %}
</div>

app/templates/main/change_password.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <h1>{{ _('Change Password') }}</h1>
  {{ super() }}
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
  </div>


{% endblock %}

app/templates/main/create_category.html.j2
{% extends 'base.html.j2' %}
{% import 'bootstrap/wtf.html' as wtf %}
{{ ckeditor.load() }}
{{ ckeditor.load(pkg_type="full") }}

{% block app_content %}
{% if form %}
</script>
  <div class="row">
        <div class="col-md-12">
            {{ wtf.quick_form(form) }}
        </div>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='category') }}
  </div>
{% endif %}
{% endblock %}

app/templates/main/create_post.html.j2
{% extends 'base.html.j2' %}
{% import 'bootstrap/wtf.html' as wtf %}
{{ ckeditor.load() }}
{{ ckeditor.load(pkg_type="full") }}

{% block app_content %}
{% if form %}
</script>
  <div class="row">
        <div class="col-md-12">
            {{ wtf.quick_form(form) }}
        </div>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='post') }}
  </div>
{% endif %}
{% endblock %}

app/templates/main/delete_post.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <h1>Delete Post</h1>
  <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
  </div>

{% endblock %}

app/templates/main/edit_category.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}
{{ ckeditor.load() }}
{{ ckeditor.load(pkg_type="basic") }}

{% block app_content %}
  <h1>{{ _('Edit Post') }}</h1>
  <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='post') }}
  </div>
{% endblock %}

app/templates/main/edit_post.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}
{{ ckeditor.load() }}
{{ ckeditor.load(pkg_type="basic") }}

{% block app_content %}
  <h1>Edit Post</h1>
  <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='post') }}
  </div>
{% endblock %}

app/templates/main/edit_profile.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}
{{ ckeditor.load() }}
{{ ckeditor.load(pkg_type="full") }}

{% block app_content %}
  <h1>{{ _('Edit Profile') }}</h1>
  <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>

        {{ ckeditor.load() }}
        {{ ckeditor.config(name='post') }}
  </div>


{% endblock %}

app/templates/main/index.html.j2
{% extends "base.html.j2" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <div class="container-fluid">
        {% for post in posts %}
          <div class="row">
            <div class="col-lg-12">
              <a href="{{ url_for('main.show_category', id=post.category_id) }}">
                {% for category in categories %}
                  {% if category.id == post.category_id %}
                    {{ category.title }}
                  {% endif %}
                {% endfor %}
              </a> -->
                <strong>{{ post.title }}</strong>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              {{ post.body|truncate(200) }}
            </div>
          </div>
          <div class="row">
            {% if post.comments|length == 0 %}
              <div class="col-lg-12">
                  <span class="badge badge-warning">{{ post.comments|length }} - {{ _('Comments left') }}</span>
              </div>
            {% else %}
              <div class="col-lg-12">
                  <a class="badge badge-secondary" href="{{ url_for('main.show_post', id=post.id) }}", id="post.id">{{ post.comments|length }} - {{ _('Comments left') }}</a>
              </div>
            {% endif %}
            {% if post.views_amount %}
              <div class="col-lg-12">
                <p class="badge badge-danger">{{ post.views_amount }} - {{ _('idiots watched this shit.') }}</p>
              </div>
            {% endif %}
            <br><br>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <a class="btn btn-success" href="{{ url_for('main.show_post', id=post.id) }}" >
                  {{ _('Read more...') }}<br>
              </a>
              <hr>
              <hr>
            </div>
          </div>
        {% endfor %}
        <div class="row">
          <div class="col-lg-12">
            <nav aria-label="...">
                 <ul class="pagination">
                     <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
                         <a class="page-link" href="{{ prev_url or '#' }}">
                             <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                         </a>
                     </li>
                     <li class="page-item next{% if not next_url %} disabled{% endif %}">
                         <a class="page-link" href="{{ next_url or '#' }}">
                             {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                         </a>
                     </li>
                 </ul>
             </nav>
          </div>
        </div>
      </div>
{% endblock %}

app/templates/main/single_category.html.j2
{% extends 'base.html.j2' %}

{% block app_content %}
<div class="container">

</div>
  <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <strong>{{ category.title }}</strong>
          <i>{{ category.description }}</i><br>
          <a class="btn btn-success" href="{{ url_for('main.edit_category', id=category.id) }}">{{ _("Edit Category") }}</a>
          <a class="btn btn-success" href="{{ url_for('main.delete_category', id=category.id) }}">{{ _("Delete Category") }}</a>
        </div>
      </div>
        {% for post in posts %}
          <div class="row">
            <div class="col-lg-12">
              <a href="{{ url_for('main.show_category', id=post.category_id) }}">
                {% for category in categories %}
                  {% if category.id == post.category_id %}
                    {{ category.title }}
                  {% endif %}
                {% endfor %}
              </a> -->
                <strong>{{ post.title }}</strong>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              {{ post.body|truncate(200) }}
            </div>
          </div>
          <div class="row">
            {% if post.comments|length == 0 %}
              <div class="col-lg-12">
                  <span class="badge badge-warning">{{ post.comments|length }} - {{ _('Comments left') }}</span>
              </div>
            {% else %}
              <div class="col-lg-12">
                  <a class="badge badge-secondary" href="{{ url_for('main.show_post', id=post.id) }}", id="post.id">{{ post.comments|length }} - {{ _('Comments left') }}</a>
              </div>
            {% endif %}
            {% if post.views_amount %}
              <div class="col-lg-12">
                <p class="badge badge-danger">{{ post.views_amount }} - {{ _('idiots watched this shit.') }}</p>
              </div>
            {% endif %}
            <br><br>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <a class="btn btn-success" href="{{ url_for('main.show_post', id=post.id) }}" >
                  {{ _('Read more...') }}<br>
              </a>
              <hr>
              <hr>
            </div>
          </div>
        {% endfor %}
        <div class="row">
          <div class="col-lg-12">
            <nav aria-label="...">
                 <ul class="pagination">
                     <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
                         <a class="page-link" href="{{ prev_url or '#' }}">
                             <span aria-hidden="true">&larr;</span> {{ _('Newer posts') }}
                         </a>
                     </li>
                     <li class="page-item next{% if not next_url %} disabled{% endif %}">
                         <a class="page-link" href="{{ next_url or '#' }}">
                             {{ _('Older posts') }} <span aria-hidden="true">&rarr;</span>
                         </a>
                     </li>
                 </ul>
             </nav>
          </div>
        </div>
      </div>
{% endblock %}

app/templates/main/single_post.html.j2
{% extends 'base.html.j2' %}

{% block app_content %}
  {% include 'main/_post.html.j2' %}
{% endblock %}

app/templates/main/user.html.j2
{% extends "base.html.j2" %}

{% block app_content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <img src="{{ user.avatar(128) }}">
      <h2>{{ _('Username: ') }}</h2>
      <a href="{{ url_for('main.user', username=user.username) }}">{{ user.username }}</a>
    </div>
    <div class="col-lg-8">
      {% if user.about_me %}
        <p>{{ user.about_me }}</p>
      {% endif %}

      {% if user.last_seen %}
        <p>{{ _('Last seen') }}: {{ moment(user.last_seen).format('LLL') }}</p>
      {% endif %}

      {% if user != current_user %}
        <p>
          <a class="btn btn-info" href="{{ url_for('main.send_message', recipient=user.username) }}">
            {{ _('Send private message') }}
          </a>
        </p>
      {% endif %}
    </div>
    <div class="col-lg-4">

    </div>
    <div class="col-lg-8">
      <p>{{ user.followers.count() }} {{ _('followers') }}, {{ user.followed.count() }} {{ _('following') }}.</p>
      {% if user == current_user %}
        <p><a class="btn btn-info" href="{{ url_for('main.edit_profile') }}">{{ _('Edit your profile') }}</a></p>
        {% if not  current_user.get_task_in_progress('export_posts') %}
          <p>
            <a class="btn btn-warning" href="{{ url_for('main.export_posts') }}">
              {{ _('Export your posts') }}
            </a>
          </p>
        {% endif %}
      {% elif not current_user.is_following(user) %}
        <p><a class="btn btn-warning" href="{{ url_for('main.follow', username=user.username) }}">{{ 'Follow' }}</a></p>
      {% else %}
        <p><a class="btn btn-danger" href="{{ url_for('main.unfollow', username=user.username) }}">{{ 'Unfollow' }}</a></p>
      {% endif %}
    </div>
  </div>

  {% for post in posts %}
    <div class="row">
      <div class="col-lg-12">
        <a href="{{ url_for('main.show_category', id=post.category_id) }}">
          {% for category in categories %}
            {% if category.id == post.category_id %}
              {{ category.title }}
            {% endif %}
          {% endfor %}
        </a> -->
        <strong>{{ post.title }}</strong>

        {{ post.body|truncate(200) }}
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <a class="btn btn-success" href="{{ url_for('main.show_post', id=post.id) }}" >
            {{ _('Read more...') }}<br>
        </a>
        <hr>
        <hr>
      </div>
    </div>
  {% endfor %}

  <div class="row">
    <div class="col-lg-12">
      <nav aria-label="...">
           <ul class="pagination">
               <li class="page-item previous{% if not prev_url %} disabled{% endif %}">
                   <a class="page-link" href="{{ prev_url or '#' }}">
                       <span aria-hidden="true">&larr;</span> {{ _('Newer Posts') }}
                   </a>
               </li>
               <li class="page-item next{% if not next_url %} disabled{% endif %}">
                   <a class="page-link" href="{{ next_url or '#' }}">
                       {{ _('Older Posts') }} <span aria-hidden="true">&rarr;</span>
                   </a>
               </li>
           </ul>
       </nav>
    </div>
  </div>
</div>


{% endblock %}

app/templates/main/user_popup.html.j2
<table class="table">
    <tr>
        <td width="64" style="border: 0px;"><img src="{{ user.avatar(64) }}"></td>
        <td style="border: 0px;">
            <p>
                <a href="{{ url_for('main.user', username=user.username) }}">
                    {{ user.username }}
                </a>
            </p>
            <small>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}
                <p>{{ _('Last seen on') }}:
                   {{ moment(user.last_seen).format('lll') }}</p>
                {% endif %}
                <p>{{ _('%(count)d followers', count=user.followers.count()) }},
                   {{ _('%(count)d following', count=user.followed.count()) }}</p>
                {% if user != current_user %}
                    {% if not current_user.is_following(user) %}
                    <a href="{{ url_for('main.follow', username=user.username) }}">
                        {{ _('Follow') }}
                    </a>
                    {% else %}
                    <a href="{{ url_for('main.unfollow', username=user.username) }}">
                        {{ _('Unfollow') }}
                    </a>
                    {% endif %}
                {% endif %}
            </small>
        </td>
    </tr>
</table>